# Generated by Django 4.0.1 on 2022-02-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_linkedin_alter_profile_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='greeting',
            field=models.CharField(default='Hi!', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, to='User.Posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricing',
            field=models.ManyToManyField(blank=True, to='User.Pricing'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, to='User.Services'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='User.Testimonials'),
        ),
    ]
