# Generated by Django 4.0.1 on 2022-02-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_profile_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='category',
            new_name='description',
        ),
    ]
