# Generated by Django 4.0.1 on 2022-02-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_category_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/portfolio')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='enable_portfolio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, to='User.Portfolio'),
        ),
    ]
