# Generated by Django 4.0.1 on 2022-02-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_portfolio_profile_enable_portfolio_profile_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
