# Generated by Django 4.0.1 on 2022-02-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='url',
        ),
    ]
