# Generated by Django 4.0.1 on 2022-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_posts_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='content',
        ),
    ]
