# Generated by Django 4.0.1 on 2022-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_description_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('to_email', models.EmailField(choices=[('gmail', 'smtp.gmail.com'), ('outlook', 'smtp-mail.outlook.com')], default='smtp.gmail.com', max_length=254)),
                ('port', models.PositiveIntegerField(choices=[('gmail', 587), ('outlook', 587)], default=587)),
            ],
        ),
    ]
