# Generated by Django 4.0.1 on 2022-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_settings_options_settings_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
