# Generated by Django 4.0.1 on 2022-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_settings_from_email_alter_settings_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='host',
            field=models.CharField(choices=[('smtp.gmail.com', 'gmail')], default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='port',
            field=models.PositiveIntegerField(choices=[(587, 'gmail')], default=587),
        ),
    ]
